apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-kube
  labels:
    app: first-kube
spec:
  replicas: 2
  selector:
    matchLabels:
      app: first-kube
  template:
    metadata:
      labels:
        app: first-kube
    spec:
      containers:
      - name: first-kube
        image: first-docker
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
