apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels: 
    app: nginx-example
spec:
  containers:
    - name: nginx-demoapp
      image: nginx
      ports:
      - containerPort: 8080
        protocol: TCP
